# Generated by Django 4.1.5 on 2023-01-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0009_alter_todomodel_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='status',
            field=models.TextField(default='Tamamlanmadı'),
        ),
    ]
